// services/api/src/common/filters/http-exception.filter.ts
import {
  ExceptionFilter,
  Catch,
  ArgumentsHost,
  HttpException,
  HttpStatus,
} from '@nestjs/common';
import { Response, Request } from 'express';

@Catch()
export class HttpExceptionFilter implements ExceptionFilter {
<<<<<<< HEAD
  catch(exception: any, host: ArgumentsHost) {
    console.error('🔥 EXCEPTION CAPTURÉE:', exception);
=======
  catch(exception: unknown, host: ArgumentsHost) {
>>>>>>> c6204d425370e1f5650e9db9e5fe71aaf6b88b80
    const ctx = host.switchToHttp();
    const response = ctx.getResponse<Response>();
    const request = ctx.getRequest<Request>();

    // Fallback to 500 Internal Server Error if it's an unhandled runtime crash
    const status =
      exception instanceof HttpException
        ? exception.getStatus()
        : HttpStatus.INTERNAL_SERVER_ERROR;
    const exceptionResponse =
      exception instanceof HttpException ? exception.getResponse() : null;

    // Pull the requestId generated by our interceptor, or fall back to a fresh tracking one
    const requestId =
      (response.getHeader('X-Request-ID') as string) || 'system-generated';

    let message: string | string[] = 'Internal server error';
    if (exceptionResponse) {
      message =
        typeof exceptionResponse === 'object' &&
        (exceptionResponse as { message?: unknown }).message
          ? ((exceptionResponse as { message: unknown }).message as
              | string
              | string[])
          : exception instanceof Error
            ? exception.message
            : message;
    }

    // Keep messages clean for array (validation) errors.
    const messages = Array.isArray(message) ? message : [message];
    // Single, human-readable string for the top-level `message` field.
    const topMessage = messages.join(', ');

    response.status(status).json({
      success: false,
      message: topMessage,
      requestId,
      error: {
        code: status,
        message: messages,
        path: request.url,
        timestamp: new Date().toISOString(),
      },
    });
  }
}
