// services/api/src/common/filters/http-exception.filter.ts
import { ExceptionFilter, Catch, ArgumentsHost, HttpException, HttpStatus } from '@nestjs/common';
import { Response, Request } from 'express';

@Catch()
export class HttpExceptionFilter implements ExceptionFilter {
  catch(exception: any, host: ArgumentsHost) {
    console.error('🔥 EXCEPTION CAPTURÉE:', exception);
    const ctx = host.switchToHttp();
    const response = ctx.getResponse<Response>();
    const request = ctx.getRequest<Request>();
    
    // Fallback to 500 Internal Server Error if it's an unhandled runtime crash
    const status = exception instanceof HttpException ? exception.getStatus() : HttpStatus.INTERNAL_SERVER_ERROR;
    const exceptionResponse = exception instanceof HttpException ? exception.getResponse() : null;

    // Pull the requestId generated by our interceptor, or fall back to a fresh tracking one
    const requestId = response.getHeader('X-Request-ID') as string || 'system-generated';

    let message = 'Internal server error';
    if (exceptionResponse) {
      message = typeof exceptionResponse === 'object' && (exceptionResponse as any).message 
        ? (exceptionResponse as any).message 
        : exception.message;
    }

    response.status(status).json({
      success: false,
      requestId,
      error: {
        code: status,
        message: Array.isArray(message) ? message : [message], // Keeps messages clean for array validations
        path: request.url,
        timestamp: new Date().toISOString(),
      },
    });
  }
}