.PHONY: build clean

build:
	./build-report.sh

clean:
	rm -f *.aux *.bbl *.blg *.fdb_latexmk *.fls *.lof *.log *.lot *.out *.synctex.gz *.toc

# Preferred:
#   make build
#
# Direct shell usage:
#   ./build-report.sh
